In [1]:
import pandas as pd
import numpy as np

In [ ]:
df_data = pd.read_csv('sort_data.csv')

In [2]:
df_data.groupby(['strain', 'condition']).size()

strain     condition         
DCLPA      canavanine            11
           heat                  12
           none                   4
           oxidative-peroxide    12
DLON       canavanine            12
           heat                  12
           none                   4
           oxidative-peroxide    11
dnak-dnaJ  canavanine            12
           heat                  12
           none                   4
           oxidative-peroxide    12
wild-type  canavanine            12
           heat                  12
           none                   4
           oxidative-peroxide    12
dtype: int64

In [3]:
df_temp = pd.read_csv('temp.csv')

In [4]:
df_temp.head()

H             g0  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  2.136532e-301   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  1.100447e-116   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   1.287890e-43   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  2.978436e-224   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  1.614357e-273   

            gi_1           gi_2           gi_3           gi_4           gi_5  \
0  4.779441e-301  3.904925e-301  3.866808e-301  3.956391e-301  2.765843e-301   
1  3.840972e-301  4.103779e-301  4.749558e-301  4.654588e-301  2.577099e-301   
2  4.010003e-301  4.559498e-301  3.226341e-301  3.341692e-301  2.152118e-301   
3  3.902480e-301  3.737874e-301  5.291465e-301  3.913702e-301  2.749729e-301   
4  4.572365e-301  4.405805e-301  5.781583e-301  3.757928e-301  2.745088e-301   

            gi_6           gi_7           gi_8  ...        gij_149  \
0  2.493762e-301  2.428022e-301  3.216526e-301  ...  4.553835e-301   
1  2.271309e-301  1.842531e-301  2.893971e-301  ...  4.556917e-301   
2  3.029543e-301  2.219205e-301  2.996498e-301  ...  4.542269e-301   
3  2.592278e-301  2.181230e-301  3.103817e-301  ...  4.547632e-301   
4  3.307957e-301  2.572398e-301  3.023278e-301  ...  4.548662e-301   

         gij_150        gij_151        gij_152        gij_153        gij_154  \
0  6.181977e-301  5.529676e-301  6.020681e-301  4.824067e-301  5.567720e-301   
1  6.166766e-301  5.529687e-301  6.013442e-301  4.817790e-301  5.561807e-301   
2  6.132736e-301  5.551599e-301  6.040012e-301  4.799150e-301  5.516324e-301   
3  6.151990e-301  5.538429e-301  5.981121e-301  4.801566e-301  5.541701e-301   
4  6.183222e-301  5.532347e-301  6.050545e-301  4.858178e-301  5.542994e-301   

         gij_155        gij_156        gij_157        gij_158  
0  3.706018e-301  5.788890e-301  4.590243e-301  5.850051e-301  
1  3.715606e-301  5.774985e-301  4.590984e-301  5.850714e-301  
2  3.696380e-301  5.754137e-301  4.543581e-301  5.832598e-301  
3  3.697797e-301  5.760019e-301  4.564285e-301  5.793276e-301  
4  3.698358e-301  5.807993e-301  4.569387e-301  5.844310e-301  

[5 rows x 176 columns]

In [5]:
df_temp[df_temp.columns[1:len(df_temp.columns)]] = df_temp[df_temp.columns[1:len(
    df_temp.columns)]].apply(lambda x: x / sum(x))

In [6]:
df_temp = df_temp.sort_values('g0', ascending=False)
df_temp.head(n=10)

H        g0      gi_1  \
393099  [0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, ...  0.216175  0.222046   
872784  [1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, ...  0.210121  0.207094   
390029  [0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, ...  0.190728  0.226209   
3303    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, ...  0.133684  0.184233   
374089  [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, ...  0.099743  0.077283   
3841    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, ...  0.026226  0.008358   
3848    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, ...  0.022873  0.009858   
374088  [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, ...  0.012776  0.010009   
3842    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, ...  0.011915  0.004786   
3850    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, ...  0.008458  0.006523   

            gi_2      gi_3      gi_4      gi_5      gi_6      gi_7      gi_8  \
393099  0.221074  0.225992  0.219828  0.238635  0.245998  0.224696  0.233032   
872784  0.212749  0.199968  0.203828  0.234999  0.227338  0.240567  0.223166   
390029  0.216134  0.230867  0.222255  0.198744  0.206981  0.191285  0.183979   
3303    0.182041  0.194412  0.183351  0.133913  0.128883  0.132502  0.129128   
374089  0.051217  0.068620  0.080077  0.087597  0.087514  0.080450  0.094108   
3841    0.019516  0.014252  0.015177  0.017819  0.019012  0.021617  0.023181   
3848    0.016659  0.007409  0.012683  0.015795  0.016254  0.017949  0.019663   
374088  0.007641  0.009536  0.008949  0.010267  0.010135  0.010456  0.011141   
3842    0.008032  0.006746  0.006739  0.008733  0.008715  0.008968  0.010251   
3850    0.008266  0.000763  0.000361  0.000387  0.000910  0.008928  0.010214   

        ...   gij_149   gij_150   gij_151   gij_152   gij_153   gij_154  \
393099  ...  0.229314  0.230691  0.227383  0.247973  0.232801  0.239646   
872784  ...  0.379467  0.395559  0.418697  0.406263  0.390849  0.393308   
390029  ...  0.149246  0.145783  0.151090  0.148081  0.150791  0.153643   
3303    ...  0.099294  0.096626  0.088937  0.088159  0.103525  0.102409   
374089  ...  0.016696  0.018511  0.009524  0.014355  0.016511  0.016934   
3841    ...  0.022534  0.019893  0.018780  0.016384  0.018321  0.016071   
3848    ...  0.019951  0.017540  0.016607  0.014810  0.016286  0.014267   
374088  ...  0.003069  0.003307  0.002026  0.002842  0.003105  0.003234   
3842    ...  0.010417  0.008974  0.008642  0.007508  0.008257  0.007333   
3850    ...  0.011203  0.010012  0.009186  0.008245  0.009177  0.008241   

         gij_155   gij_156   gij_157   gij_158  
393099  0.224301  0.239339  0.224622  0.235031  
872784  0.402454  0.395899  0.386468  0.393709  
390029  0.155966  0.157800  0.152949  0.144301  
3303    0.093398  0.099671  0.096461  0.097549  
374089  0.008802  0.018905  0.016675  0.017939  
3841    0.020713  0.014880  0.022140  0.019243  
3848    0.018609  0.013409  0.019736  0.017150  
374088  0.001808  0.002919  0.002500  0.003253  
3842    0.009449  0.006790  0.010300  0.008789  
3850    0.010198  0.007648  0.010749  0.009819  

[10 rows x 176 columns]

In [7]:
threshold = 0.05
# total_sample = sum(n_biopsies_I)
# df_p = df_temp[(df_temp[df_temp.columns[-(total_sample):]]
#                 > threshold).any(axis=1)]

df_p = df_temp[df_temp['g0']> threshold]

df_p[df_p.columns[1:len(df_p.columns)]] = df_p[df_p.columns[1:len(
    df_p.columns)]].apply(lambda x: x / sum(x))

df_p = df_p.sort_values('g0', ascending=False)

row = ['H'] + ['Top_Level'] + list(df_data.groupby(['strain', 'condition']).groups.keys()) + list(df_data.groupby(['strain', 'condition', 'slevel', 'rep']).groups.keys())
row_condition = pd.DataFrame([row], columns=list(df_p.columns))

df_annote =  pd.concat([row_condition, df_p])

# df_annote.to_csv('inference_oak_1.csv', index=False)

/Users/shaihe/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3065: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


In [41]:
locus_att = pd.read_csv('locus_attribute.tab', sep='\t')
locus_att = locus_att[['locus_tag', 'Name', 'description']].drop_duplicates(subset=['locus_tag'])
locus_tag = df_data.columns[7:]
df_locus_tag = pd.DataFrame(locus_tag)
df_locus_tag.columns = ['locus_tag']
df_att = df_locus_tag.merge(locus_att, on='locus_tag', how='left')

In [42]:
df_att

locus_tag        Name  \
0     CCNA_00001  CCNA_00001   
1     CCNA_00002  CCNA_00002   
2     CCNA_00003  CCNA_00003   
3     CCNA_00004  CCNA_00004   
4     CCNA_00005        dnaQ   
...          ...         ...   
4079  CCNA_R0195         NaN   
4080  CCNA_R0196  CCNA_R0196   
4081  CCNA_R0197  CCNA_R0197   
4082  CCNA_R0198  CCNA_R0198   
4083  CCNA_R0199  CCNA_R0199   

                                            description  
0     ATP/GTP-binding protein;protein_id=YP_00251537...  
1     septum formation protein Maf;protein_id=YP_002...  
2     shikimate 5-dehydrogenase;protein_id=YP_002515...  
3       dephospho-CoA kinase;protein_id=YP_002515379.1;  
4                                                   NaN  
...                                                 ...  
4079                                                NaN  
4080                               small non-coding RNA  
4081                               small non-coding RNA  
4082                               small non-coding RNA  
4083                               small non-coding RNA  

[4084 rows x 3 columns]

In [43]:
# L = 4084
len(df_data.columns[7:])
n_cluster = len(df_p)
H_matrix = np.zeros((n_cluster,L), dtype='int')
H_matrix_str = np.asarray(df_p['H'])
for i in range(n_cluster):
    H_matrix_str[i] = H_matrix_str[i].replace(", ", "").replace("[", "").replace("]", "")

for i in range(n_cluster):
    for j in range(L):
        if H_matrix_str[i][j] == "0":
            H_matrix[i,j] = int(0)
        if H_matrix_str[i][j] == "1":
            H_matrix[i,j] = int(1)

df_H = pd.DataFrame(H_matrix.T)
df_H["locus_tag"] = df_att['locus_tag']
df_H['Gene_Name'] = df_att['Name']
df_H['Description'] = df_att['description']

cols = list(df_H.columns)
cols = [cols[-3]] + [cols[-2]] + [cols[-1]] + cols[:-3]
df_H = df_H[cols]

# df_H = df_H[["locus_tag", 0, 1, 2, 3, 4]]
# df_H.columns = ["locus_tag", "top_1", "top_2", "top_3", "top_4", "top_5"]

df_H.to_csv('H_matrix_oak_1.csv', index=False)

In [11]:
temp =np.load('threshold.npy')

In [12]:
temp

array([[ 1, 21],
       [ 1, 64],
       [ 1, 38],
       ...,
       [ 3, 15],
       [ 1, 11],
       [ 1, 10]])

In [13]:
temp[13]

array([ 1, 65])

In [23]:
temp_1 = np.load('peter_UC_processed.csv_threshold.npy')

In [31]:
temp_1[372]

array([  0, 102])

In [25]:
temp_1[374]

array([  0, 100])

In [6]:
temp[21]

array([ 0, 22])

In [7]:
temp[0]

array([ 0, 21])

In [8]:
temp[0:10]

array([[ 0, 21],
       [ 0, 64],
       [ 0, 38],
       [ 0, 10],
       [ 0, 10],
       [ 5, 30],
       [ 0, 10],
       [ 0, 10],
       [ 0, 25],
       [ 0,  7]])